Add certbot get and set binaries for cloudflare token and cron

diff --git a/overlay/usr/local/bin/certbotset b/overlay/usr/local/bin/certbotset
--- a/overlay/usr/local/bin/certbotset
+++ b/overlay/usr/local/bin/certbotset
@@ -1,13 +1,30 @@
 #!/bin/sh
 
-cloudflare() {
+set_cloudflare() {
     echo "dns_cloudflare_api_token = ${cloudflare_api_key}" > /usr/local/certbot/.secrets/cloudflare.ini
 }
 
-if [ "$1" == "certbot_cloudflare_api_token" ]
+set_cron() {
+    echo "$cron_expression" /usr/local/certbot/update_certs.sh > new_cron
+
+    if crontab new_cron
+    then
+      sysrc -f /etc/rc.conf certbot_cron="$cron_expression"
+      rm new_cron
+    else
+      echo "Invalid cron expression"
+      exit 1
+    fi
+}
+
+if [ "$1" == "cloudflare_api_token" ]
 then
     cloudflare_api_key="$2"
-    cloudflare
+    set_cloudflare
+elif [ "$1" = "cron" ]
+then
+    cron_expression="$2"
+    set_cron
 else
     echo "Unknown option"
 fi
